### ISSUE TITLE
When will master be released?

### ISSUE THREAD

**Issue by kyle-wong-knewton** [Thriftpy/thriftpy2#191]
Im having deserialization issues that are fixed with this commit PR: https://github.com/Thriftpy/thriftpy2/pull/164, but i notice it haven't been any releases since this fix was merged. Are there plans to do a release soon?

**Comment by rlratzel** [comment]
We're also hoping to get a release that includes the recently merged PR #159 (thank you @aiudirog @ethe) which removes the deprecation warnings in 0.4.14.  If there was a 0.4.15 release, I would update the conda-forge [thriftpy2-feedstock](https://github.com/conda-forge/thriftpy2-feedstock/blob/main/recipe/meta.yaml) for a 0.4.15 conda package on conda-forge. Since our project requires a `linux-aarch64` conda package for thriftpy2 anyway, it would be highly preferable to have the latest merged PRs in an updated release, if possible.

**Comment by ethe** [comment]
0.4.15 released, thanks for your question
